version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /tmp
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  postgres: