version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /tmp
  web:
    build: .
    image: django-scraper__web
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: scraper.docker
      VIRTUAL_PORT: 80

  run_cronjobs:
    image: django-scraper__web
    restart: unless-stopped
    depends_on:
      - web
    command: python manage.py runcrons
volumes:
  postgres: