# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_counts', models.TextField()),
                ('top_10_words', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_author', to='scraper.Author')),
            ],
        ),
        migrations.CreateModel(
            name='TotalStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('word_counts', models.TextField()),
                ('top_10_words', models.TextField()),
            ],
        ),
    ]
